# Generated by Django 4.1.1 on 2022-09-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='procedimentos',
            field=models.ManyToManyField(to='consultas.procedimento'),
        ),
    ]
